version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
